POST http://localhost:5000/auth/signup
Content-Type: application/json

{
    "email": "Chrispool228@gmail.com",
    "password": "Poolguy123"
}

###

POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email": "Chrispool228@gmail.com",
    "password": "Poolguy123"
}

###

POST http://localhost:5000/auth/token
Content-Type: application/json

###

GET http://localhost:5000/cart/view
Content-Type: application/json

###

DELETE http://localhost:5000/cart/remove
Content-Type: application/json

{
    "productId": 1
}

###

PATCH http://localhost:5000/cart/update
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkNocmlzcG9vbDIyOEBnbWFpbC5jb20iLCJpZCI6MTMsImlhdCI6MTc3MDUzMDQ5MCwiZXhwIjoxNzcwNTMxMzkwfQ.p5Z36kjajr5DD_1mB9jI6W46COuO2XRirfb54fgmRpU
Content-Type: application/json

{
    "productId": 1,
    "quantity": 5
}