on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build and Run Docker Services
      run: docker compose -f docker-compose.yml -f docker-compose.ci.yml up --build --abort-on-container-failure
